backend:
  name: git-gateway
  branch: main
  commit_messages:
    create: "Create {{collection}} “{{slug}}”"
    update: "Update {{collection}} “{{slug}}”"
    delete: "Delete {{collection}} “{{slug}}”"
    uploadMedia: "[skip ci] Upload “{{path}}”"
    deleteMedia: "[skip ci] Delete “{{path}}”"

local_backend: true

media_folder: static/img
public_folder: /img

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Featured Post", name: "featuredpost", widget: "boolean" }
      - { label: "Featured Image", name: "featuredimage", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Tags", name: "tags", widget: "list" }

  - name: "kursy"
    label: "Kursy"
    folder: "src/pages/kursy"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Template Key", name: "templateKey", widget: "hidden", default: "course-page" }
      - { label: "Path", name: "path", widget: "string", default: "/courses/{{slug}}" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Navigation priority", name: "navigationpriority", widget: "string" }          
      - { label: "Featured image", name: "featuredimage", widget: "image" }
      - { label: "Background color", name: "color", widget: "color" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Card heading", name: "cardheading", widget: "string" }
      - { label: "Card color", name: "cardcolor", widget: "color" }
      - { label: "Card List", name: "cardlist", widget: "list", field: { label: "Item", name: "item", widget: "string" } }

  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Landing Page"
        name: "index"
        fields:
          - { name: "templateKey", label: "Template Key", widget: "hidden" }
          - { name: "title", label: "Title", widget: "string" }
          - { name: "heading", label: "Heading", widget: "string" }
          - { name: "description", label: "Description", widget: "string" }
          - name: "features"
            label: "Features"
            widget: "list"
            fields:
              - { name: "svgIcon", label: "Icon", widget: "string" }
              - { name: "text", label: "Text", widget: "string" }
          - name: "courses"
            label: "Courses"
            widget: "list"
            fields:
              - { name: "title", label: "Title", widget: "string" }
              - { name: "body", label: "Body", widget: "string" }
              - { name: "headerColor", label: "Header Color", widget: "color" }
              - { name: "btnLink", label: "Button Link", widget: "string" }
          - name: "individualCourses"
            label: "Individual Courses"
            widget: "list"
            fields:
              - { name: "title", label: "Title", widget: "string" }
              - { name: "headerColor", label: "Header Color", widget: "color" }
              - { name: "btnLink", label: "Button Link", widget: "string" }
              - name: "selectedCourse"
                label: "Select a Course"
                widget: "relation"
                collection: "courses"  # Fetch from the courses collection
                search_fields: ["title"]  # Search by course title
                value_field: "{{slug}}"  # Store the course slug for linking
                display_fields: ["title"]  # Show course titles in the dropdown
                multiple: false
                
          - name: "sampleInfoBox"
            label: "Sample Info Box"
            widget: "object"
            fields:
              - { name: "title", label: "Title", widget: "text" }
              - { name: "btnLink", label: "Button Link", widget: "string" }
              - { name: "btnText", label: "Button Text", widget: "string" }
              - { name: "backgroundColor", label: "Background Color", widget: "color" }

      - file: "src/pages/about/index.md"
        label: "About"
        name: "about"
        slug: "{{slug}}"
        fields:
          - { label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page" }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Navigation priority", name: "navigationpriority", widget: "number" }              
          - { label: "Teachers", name: "teachers", widget: "list", fields: [
              { label: "Teacher Name", name: "name", widget: "string" },
              { label: "Teacher Role", name: "role", widget: "string" },
              { label: "Teacher Bio", name: "bio", widget: "markdown" },
              { label: "Teacher Photo", name: "photo", widget: "image" }
            ]
          }
          - { label: "Body", name: "body", widget: "markdown" }
          
      - label: "Contact Page"
        name: "contact"
        file: "src/pages/contact/index.md"
        fields:
          - { label: "Template Key", name: "templateKey", widget: "hidden", default: "contact-page" }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Navigation priority", name: "navigationpriority", widget: "string" }          
          - { label: "Phone", name: "phone", widget: "string" }
          - { label: "Email", name: "email", widget: "string" }
          - { label: "Address", name: "address", widget: "string" }
          - { label: "Facebook Link", name: "facebook", widget: "string" }
          - { label: "Instagram Link", name: "instagram", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
