backend:
  name: git-gateway
  branch: main
  commit_messages:
    create: "Create {{collection}} “{{slug}}”"
    update: "Update {{collection}} “{{slug}}”"
    delete: "Delete {{collection}} “{{slug}}”"
    uploadMedia: "[skip ci] Upload “{{path}}”"
    deleteMedia: "[skip ci] Delete “{{path}}”"

local_backend: true
media_folder: static/img
public_folder: /img

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Featured Post", name: "featuredpost", widget: "boolean" }
      - { label: "Featured Image", name: "featuredimage", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Tags", name: "tags", widget: "list" }

  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Landing Page"
        name: "index"
        fields:
          - { name: "templateKey", label: "Template Key", widget: "hidden" }
          - { name: "title", label: "Title", widget: "string" }
          - { name: "heading", label: "Heading", widget: "string" }
          - { name: "description", label: "Description", widget: "string" }
          - name: "features"
            label: "Features"
            widget: "list"
            fields:
              - { name: "svgIcon", label: "Icon", widget: "string" }
              - { name: "text", label: "Text", widget: "string" }
          - name: "courses"
            label: "Courses"
            widget: "list"
            fields:
              - { name: "title", label: "Title", widget: "string" }
              - { name: "body", label: "Body", widget: "string" }
              - { name: "headerColor", label: "Header Color", widget: "color" }
              - { name: "btnLink", label: "Button Link", widget: "string" }
          - name: "individualCourses"
            label: "Individual Courses"
            widget: "list"
            fields:
              - { name: "title", label: "Title", widget: "string" }
              - { name: "headerColor", label: "Header Color", widget: "color" }
              - { name: "btnLink", label: "Button Link", widget: "string" }
          - name: "sampleInfoBox"
            label: "Sample Info Box"
            widget: "object"
            fields:
              - { name: "title", label: "Title", widget: "text" }
              - { name: "btnLink", label: "Button Link", widget: "string" }
              - { name: "btnText", label: "Button Text", widget: "string" }
              - { name: "backgroundColor", label: "Background Color", widget: "color" }

      - file: "src/pages/about/index.md"
        label: "About"
        name: "about"
        fields:
          - { label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page" }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
          - { label: "Description", name: "desc", widget: "string" }
          - { label: "Menu", name: "menutest", widget: "string" }

      - file: "src/pages/products/index.md"
        label: "Products Page"
        name: "products"
        fields:
          - { label: "Template Key", name: "templateKey", widget: "hidden", default: "product-page" }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Image", name: "image", widget: "image" }
          - { label: "Heading", name: "heading", widget: "string" }
          - { label: "Description", name: "description", widget: "string" }
          - name: "intro"
            label: "Intro"
            widget: "object"
            fields:
              - { label: "Heading", name: "heading", widget: "string" }
              - { label: "Description", name: "description", widget: "text" }
              - name: "blurbs"
                label: "Blurbs"
                widget: "list"
                fields:
                  - { label: "Image", name: "image", widget: "image" }
                  - { label: "Text", name: "text", widget: "text" }
          - name: "main"
            label: "Main"
            widget: "object"
            fields:
              - { label: "Heading", name: "heading", widget: "string" }
              - { label: "Description", name: "description", widget: "text" }
              - name: "image1"
                label: "Image 1"
                widget: "object"
                fields:
                  - { label: "Image", name: "image", widget: "image" }
                  - { label: "Alt", name: "alt", widget: "string" }
              - name: "image2"
                label: "Image 2"
                widget: "object"
                fields:
                  - { label: "Image", name: "image", widget: "image" }
                  - { label: "Alt", name: "alt", widget: "string" }
              - name: "image3"
                label: "Image 3"
                widget: "object"
                fields:
                  - { label: "Image", name: "image", widget: "image" }
                  - { label: "Alt", name: "alt", widget: "string" }
          - { label: "Full Image", name: "full_image", widget: "image" }

      - file: "src/pages/about/test/index.md"
        label: "Test"
        name: "test"
        fields:
          - { label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page" }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
          - { label: "Description", name: "desc", widget: "string" }
          - { label: "Menu", name: "menutest", widget: "string" }
